myhm/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('templates.urls'))

]

templates/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils import timezone
from django.contrib.auth.models import User

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = [
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
        ('staff', 'Staff'),
        ('admin', 'Admin'),
    ]
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='patient')
    dob = models.DateField(null=True, blank=True)

    groups = models.ManyToManyField(Group, related_name='customuser_groups', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_permissions', blank=True)

    def __str__(self):
        return self.username


class Patient(models.Model):
    SEX_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    BLOOD_TYPE_CHOICES = [
        ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'),
        ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'),
    ]
    MARITAL_STATUS_CHOICES = [
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Divorced', 'Divorced'),
        ('Widowed', 'Widowed'),
    ]

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='patients', null=True, blank=True)
    dob = models.DateField()
    sex = models.CharField(max_length=6, choices=SEX_CHOICES, default='Other')  
    blood_type = models.CharField(max_length=3, choices=BLOOD_TYPE_CHOICES, default='O+') 
    marital_status = models.CharField(max_length=10, choices=MARITAL_STATUS_CHOICES, default='Single')  
    city = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    state = models.CharField(max_length=20)
    pin_code = models.CharField(max_length=10)
    phoneNo = models.CharField(max_length=12)
    email = models.EmailField()
    emergencyContactName = models.CharField(max_length=50)
    emergencyContactPhone = models.CharField(max_length=12)
    emergencyContactRelation = models.CharField(max_length=50)
    registration_date = models.DateField(auto_now_add=True)
    medical_history = models.TextField()
    allergies = models.TextField()

    def __str__(self):
        return self.user.username


class Dept(models.Model):
    id = models.AutoField(primary_key=True)  
    dept_name = models.CharField(max_length=50)
    no_doctors = models.IntegerField(default=0)  
    no_staff = models.IntegerField(default=0)  
    dept_phone = models.CharField(max_length=12)
    floor_number = models.IntegerField(default=1)  
    specialty = models.CharField(max_length=100)
    background_image = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.dept_name

    def get_absolute_url(self):
        return reverse('dept-detail', kwargs={'pk': self.pk})


class Doctor(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='doctors', null=True, blank=True)
    position = models.CharField(max_length=100, default='General Physician')  
    education = models.CharField(max_length=200, default='MBBS')  
    experience = models.CharField(max_length=50, default='0 years') 
    fees = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  
    department = models.ForeignKey(Dept, on_delete=models.CASCADE, related_name='doctors', null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"


STAFF_ROLE_CHOICES = [
    ('Nurse', 'Nurse'),
    ('Receptionist', 'Receptionist'),
    ('Administrator', 'Administrator'),
    ('Pharmacist', 'Pharmacist'),
    ('Technician', 'Technician'),
]
SHIFT_CHOICES = [
    ('Morning', 'Morning'),
    ('Evening', 'Evening'),
    ('Night', 'Night'),
]

class Staff(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='staffs', null=True, blank=True)
    staff_role = models.CharField(max_length=20, choices=STAFF_ROLE_CHOICES, default='Nurse') 
    salary = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)  
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, null=True, blank=True)
    staff_shift = models.CharField(max_length=10, choices=SHIFT_CHOICES, default='Morning') 
    phoneNo = models.CharField(max_length=12)
    email = models.EmailField()
    address = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user.username}"

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"


class Procedure(models.Model):
    id = models.AutoField(primary_key=True)  
    name = models.CharField(max_length=100)
    fees = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  
    department = models.ForeignKey(Dept, on_delete=models.CASCADE, related_name='procedures', null=True, blank=True)

    def __str__(self):
        return self.name



class Appointment(models.Model):
    id = models.AutoField(primary_key=True)  
    patient = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='appointments_as_patient', null=True, blank=True)
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='appointments_as_doctor', null=True, blank=True)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)
    fees = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  
    payment_mode = models.CharField(max_length=20, default='Not Paid')
    status = models.CharField(max_length=20, default='Pending')
    mode = models.CharField(max_length=20, default='In-Person')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['doctor', 'date', 'time'], name='unique_appointment')
        ]

    def save(self, *args, **kwargs):
        if not self.patient or not self.doctor:
            raise ValueError("Patient and Doctor must be specified")
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Appointment {self.id} - {self.patient.first_name} {self.patient.last_name} with {self.doctor.username} on {self.date} at {self.time}'


class Room(models.Model):
    id = models.AutoField(primary_key=True)  
    ROOM_TYPE_CHOICES = [
        ('General', 'General'),
        ('Single', 'Single'),
        ('Double', 'Double'),
        ('ICU', 'ICU'),
        ('VIP', 'VIP'),
    ]
    AVL_STATUS_CHOICES = [
        ('Vacant', 'Vacant'),
        ('Occupied', 'Occupied'),
        ('Under Maintenance', 'Under Maintenance'),
    ]

    room_type = models.CharField(max_length=10, choices=ROOM_TYPE_CHOICES)
    room_floor = models.IntegerField(default=1)  
    avl_status = models.CharField(max_length=20, choices=AVL_STATUS_CHOICES, default='Vacant') 
    room_rate_per_day = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)  

    def __str__(self):
        return f"Room {self.id} - {self.room_type}"


class AdmittedPatient(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='admitted_patients', null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True, blank=True)
    admit_date = models.DateField()
    discharge_date = models.DateField(null=True, blank=True)
    medProcedure = models.CharField(max_length=100, default='General Checkup')  
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='admitted_patients_doctor', null=True, blank=True)
    staff = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    reason_for_admission = models.TextField()
    treatment_plan = models.TextField()

    @property
    def patient_name(self):
        return self.user.username  

    def __str__(self):
        return f"Admitted {self.user.username}"


class Billing(models.Model):
    id = models.AutoField(primary_key=True)  
    BILL_STATUS_CHOICES = [
        ('Paid', 'Paid'),
        ('Pending', 'Pending'),
    ]
    PAYMENT_MODE_CHOICES = [
        ('Online', 'Online'),
        ('Cash', 'Cash'),
        ('Cheque', 'Cheque'),
        ('Credit Card', 'Credit Card'),
    ]

    patient = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='billings', null=True, blank=True)
    admission = models.ForeignKey(AdmittedPatient, on_delete=models.CASCADE, related_name='billings', null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  
    status = models.CharField(max_length=10, choices=BILL_STATUS_CHOICES, default='Pending')
    payment_mode = models.CharField(max_length=20, choices=PAYMENT_MODE_CHOICES, default='Cash')

    @property
    def bill_status(self):
        return self.status

    def __str__(self):
        return f"Billing for {self.patient.username} - {self.total_amount} ({self.status})"

class MedicalRecord(models.Model):
    patient = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='medical_records', null=True, blank=True)
    doctor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='medical_records_doctor', null=True, blank=True)
    medical_history = models.TextField()
    diagnosis = models.TextField(null=True, blank=True)
    treatment_plan = models.TextField(null=True, blank=True)
    prescription = models.TextField(null=True, blank=True)
    record_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"Medical Record for {self.patient.username} on {self.record_date}"


class Equipments(models.Model):
    id = models.AutoField(primary_key=True)  
    MAINTENANCE_STATUS_CHOICES = [

templates/forms.py
from django import forms
from django.utils import timezone
from .models import *
from datetime import timedelta


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = [
            'user', 'dob', 'sex', 'blood_type', 'marital_status',
            'city', 'address', 'state', 'pin_code', 'phoneNo',
            'email', 'emergencyContactName', 'emergencyContactPhone',
            'emergencyContactRelation', 'medical_history', 'allergies'
        ]



class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['doctor', 'date', 'time'] 

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['doctor'].queryset = CustomUser.objects.filter(user_type='doctor')
        
        self.fields['date'].widget.attrs.update({
            'min': timezone.now().date().isoformat(),
            'max': (timezone.now() + timedelta(days=3)).date().isoformat()
        })

    def clean(self):
        cleaned_data = super().clean()
        doctor = cleaned_data.get("doctor")
        date = cleaned_data.get("date")
        time = cleaned_data.get("time")

        if doctor and date and time:
            if Appointment.objects.filter(doctor=doctor, date=date, time=time).exists():
                raise forms.ValidationError('The selected time slot is already booked.')

        return cleaned_data

    def get_available_time_slots(self, doctor, date):
        """Fetch available time slots for a given doctor on a specified date."""
        all_slots = ['09:00', '10:00', '11:00', '12:00', '14:00', '15:00', '16:00']
        booked_times = Appointment.objects.filter(doctor=doctor, date=date).values_list('time', flat=True)
        available_slots = [slot for slot in all_slots if slot not in booked_times]
        return available_slots
        


class AppointmentFilterForm(forms.Form):
    date = forms.DateField(
        required=True,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Select Date'
    )

templates/templates/templates/appointment_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appointment Success</title>
    <link rel="stylesheet" type="text/css" href="../../static/templates/appointment_success.css">
</head>
<body>
    <h1>Your appointment has been successfully booked!</h1>
    <a href="{% url 'main-home' %}">Return to Home</a>
</body>
</html>

templates/templates/templates/bookAnAppointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Appointment</title>
    <link rel="stylesheet" href="../../static/templates/bookAnAppointment.css">  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <h1>Book Appointment</h1>
        <a href="{% url 'main-home' %}" class="home-button">Home</a> 
    </header>

    <form method="post">
        {% csrf_token %}
        
        {{ form.patient.label_tag }} {{ form.patient }}
        {{ form.doctor.label_tag }} {{ form.doctor }}

        {{ form.date.label_tag }} {{ form.date }}

        <label for="time">Available Time Slots:</label>
        <select id="time" name="time">
            <option value="">Select a time</option>
        </select>

        <div>
            <label>Fees: 500 (Fixed)</label>
        </div>
        {{ form.payment_mode.label_tag }} {{ form.payment_mode }}
       <br>
       
       <div>
           <label>Status: Not Paid. Pay during the appointment.</label>
        </div>
        
        <br>
        {{ form.mode.label_tag }} {{ form.mode }}

        <button type="submit">Book Appointment</button>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#id_doctor, #id_date").change(function() {
                var doctorId = $("#id_doctor").val();
                var date = $("#id_date").val();
    
                if (doctorId && date) {
                    $.ajax({
                        url: "{% url 'get_available_times' %}",  
                        data: {
                            'doctor_id': doctorId,
                            'date': date
                        },
                        success: function(data) {
                            var $timeSelect = $("#time");
                            $timeSelect.empty();  
                            
                            if (data.available_slots.length === 0) {
                                $timeSelect.append($('<option>').text('All slots booked').attr('value', ''));
                            } else {
                                $timeSelect.append($('<option>').text('Select a time').attr('value', ''));
                                $.each(data.available_slots, function(index, value) {
                                    $timeSelect.append($('<option>').text(value).attr('value', value));
                                });
                            }
                        }
                    });
                }
            });
        });
    </script>
    
    
    
    
    
</body>
</html>

templates/templates/templates/department_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ dept.dept_name }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../../static/templates/home.css">
</head>
<body>
    <header>
        <container style="display: flex; align-items: center;">
            <img src="../../static/images/logo.png" alt="XYZ Hospital Logo" width="150" style="margin-left: 10px;">
            <h1 class="hname" style="margin: 0;margin-left: -30px;">XYZ</h1>
        </container>
        <div class="auth-buttons">
            {% if user.is_authenticated and user.user_type == 'patient' %}
                <button class="profile-btn">
                    <a href="{% url 'patientDashboard' %}" style="text-decoration: none;">
                        <i class="fa fa-user"></i> Profile
                    </a>
                </button>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="text-decoration: none;">Logout</button>
                </form>
            {% else %}
                <button class="login-btn">
                    <a href="{% url 'login' %}" style="text-decoration: none;">Login</a>
                </button>
                <button class="signup-btn">
                    <a href="{% url 'registerAsPatient' %}" style="text-decoration: none;">Sign Up</a>
                </button>
            {% endif %}
        </div>
        <div class="top">
            <div class="top1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/>
                </svg>
                <p>Katni(M.P.)</p>
            </div>
            <div class="top2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                </svg>
                <p>123456789</p>
            </div>
        </div>
    </header>

    <div class="nav" style="justify-content: space-between;">
        <ul>
            <li>
                <a href="{% url 'main-home' %}" style="text-decoration: none;">Home</a>
            </li>
            <li>
                <a href="{% url 'medicalRecord' %}" style="text-decoration: none;">Medical Record</a>
            </li>
            <li>
                <a href="#" style="text-decoration: none; color: white;">Specialities</a>
                <ul class="dropdown">
                    {% for department in departments %}
                        <li><a href="{% url 'dept_detail' department.pk %}" style="text-decoration: none;">{{ department.dept_name }}</a></li>
                    {% empty %}
                        <li>No departments available.</li>
                    {% endfor %}
                </ul>
            </li>
            <li>
                <a href="{% url 'main-home' %}#aboutUs" style="text-decoration: none;">About Us</a>
            </li>
            <li>
                <a href="{% url 'main-home' %}#contactUs" style="text-decoration: none;">Contact Us</a>
            </li>
        </ul>
       
        <img src="../../static/images/inss.png" alt="Heatlh First" width="200px">
    </div>

    <div class="header" style="background-image: url('{{ dept.background_image }}');">
        <div class="overlay">
            <h1>{{ dept.dept_name }}</h1>
        </div>
    </div>

    <h2>Our Team of Experts</h2>
    <div class="doctor-list">
        {% for doctor in doctors %}
            <container class="doctor">
                <container class="doctor-info">
                    <h3>{{ doctor.full_name }}</h3>
                    <p class="position">{{ doctor.position }}</p>
                    <p class="education">{{ doctor.education }}</p>
                    <p class="experience">Experience: {{ doctor.experience }}</p>
                    <p class="fees">Fees: ₹{{ doctor.fees }}</p>
                </container>
                <button class="appointment-button" >Book Appointment</button>
            </container>
        {% empty %}
            <p>No doctors available in this department.</p>
        {% endfor %}
        </div>

    <container class="procedures-list">
        <h2>Medical Procedures for {{ dept.dept_name }}</h2>
        {% for procedure in procedures %}
            <div class="procedure">
                <div class="procedure-info">
                    <h3>{{ procedure.name }}</h3>
                    <p class="fees">Fees: ₹{{ procedure.fees }}</p>
                </div>
            </div>
        {% empty %}
            <p>No procedures available for this department.</p>
        {% endfor %}
    </container>
</body>
</html>

templates/templates/templates/departments.html
<div class="header" style="background-image: url('{{ dept.background_image }}');">
    <div class="overlay">
        <h1>{{ dept.dept_name }}</h1>
    </div>
</div>

<div class="doctor-list">
    <h2>Our Team of Experts</h2>
    {% for doctor in doctors %}
    <div class="doctor">
        <div class="doctor-info">
            <h3>{{ doctor.name }}</h3>
            <p class="position">{{ doctor.position }}</p>
            <p class="education">{{ doctor.education }}</p>
            <p class="experience">Experience: {{ doctor.experience }}</p>
            <p class="fees">Fees: ₹{{ doctor.fees }}</p>
        </div>
        <button class="appointment-button">Book Appointment</button>
    </div>
    {% endfor %}
</div>

<div class="procedures-list">
    <h2>Medical Procedures for {{ dept.dept_name }}</h2>
    {% for procedure in procedures %}
    <div class="Procedure">
        <div class="Procedure-info">
            <h3>{{ procedure.name }}</h3>
            <p class="fees">Fees: ₹{{ procedure.fees }}</p>
        </div>
    </div>
    {% endfor %}
</div>

templates/templates/templates/dept_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ dept.dept_name }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../../static/templates/dept_details.css">
</head>
<body>
    <header>
        <container style="display: flex; align-items: center;">
            <img src="../../static/images/logo.png" alt="XYZ Hospital Logo" width="150" style="margin-left: 10px;">
            <h1 class="hname" style="margin: 0;margin-left: -30px;">XYZ</h1>
        </container>
        <div class="auth-buttons">
            {% if user.is_authenticated and user.user_type == 'patient' %}
                <button class="profile-btn">
                    <a href="{% url 'patientDashboard' %}" style="text-decoration: none;">
                        <i class="fa fa-user"></i> Profile
                    </a>
                </button>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="text-decoration: none;">Logout</button>
                </form>
            {% else %}
                <button class="login-btn">
                    <a href="{% url 'login' %}" style="text-decoration: none;color:black;">Login</a>
                </button>
                <button class="signup-btn">
                    <a href="{% url 'registerAsPatient' %}" style="text-decoration: none;">Sign Up</a>
                </button>
            {% endif %}
        </div>
        <div class="top">
            <div class="top1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/>
                </svg>
                <p>Katni(M.P.)</p>
            </div>
            <div class="top2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                </svg>
                <p>123456789</p>
            </div>
        </div>
    </header>

    <div class="nav" style="justify-content: space-between;">
        <ul>
            <li>
                <a href="{% url 'main-home' %}" style="text-decoration: none;">Home</a>
            </li>
            <a href="{% url 'medicalRecord' %}" style="text-decoration: none;">  
                <li>Medical Record</li>
            </a>
            <li>
                <a href="#" style="text-decoration: none;color: white">Specialities</a>
                <ul class="dropdown">
                    {% for department in departments %}
                        <li><a href="{% url 'dept_detail' department.pk %}" style="text-decoration:none; color: black;">{{ department.dept_name }}</a></li>
                    {% empty %}
                        <li>No departments available.</li>
                    {% endfor %}
                </ul>
            </li>
            <li>
                <a href="{% url 'main-home' %}#aboutUs" style="text-decoration: none;">About Us</a>
            </li>
            <li>
                <a href="{% url 'main-home' %}#contactUs" style="text-decoration: none;">Contact Us</a>
            </li>
        </ul>
        <img src="../../static/images/inss.png" alt="Heatlh First" width="200px">
    </div>
    <container class="header">
        <container class="overlay">
            <h1 id="'dname">{{ department.dept_name }}</h1>
        </container>
    </container>

    <h2>Our Team of Experts</h2>
    <div class="doctor-list">
        {% for doctor in doctors %}
            <container class="doctor">
                <container class="doctor-info">
                    <h3>{{ doctor.full_name }}</h3>
                    <p class="position">{{ doctor.position }}</p>
                    <p class="education">{{ doctor.education }}</p>
                    <p class="experience">Experience: {{ doctor.experience }}</p>
                    <p class="fees">Fees: ₹{{ doctor.fees }}</p>
                </container>
                <button class="appointment-button" ><a href="{% url 'bookAnAppointment' %}" style="text-decoration: none; color: inherit;">
                    Book Appointment
                </a></button>
            </container>
        {% empty %}
            <p>No doctors available in this department.</p>
        {% endfor %}
        </div>

        <h2>Medical Procedures for {{ department.dept_name }}</h2>
    <div class="procedures-list">
        {% for procedure in procedures %}
            <container class="procedure">
                <container class="procedure-info">
                    <h3>{{ procedure.name }}</h3>
                    <p class="fees">Fees: ₹{{ procedure.fees }}</p>
                </container>
            </container>
        {% empty %}
            <p>No procedures available for this department.</p>
        {% endfor %}
        </div>
</body>
</html>

templates/templates/templates/errorpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Error</p>
</body>
</html>